# Generated by Django 5.2.8 on 2025-11-29 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0003_cart_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Informatique & Electro', 'Inf'), ('Chaussures', 'SHOES'), ('Lecture', 'READING'), ('Habits', 'CLOTHES')], default='Inf', max_length=100, unique=True),
        ),
    ]
