# Generated by Django 5.2.8 on 2025-11-30 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0005_alter_category_name_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
