# Generated by Django 5.2.8 on 2025-11-30 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0006_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
    ]
