# Generated by Django 5.2.8 on 2026-01-09 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0008_remove_order_customer_order_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
