# Generated by Django 5.2.8 on 2026-02-02 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0009_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='Noura.JPG', upload_to='products/'),
        ),
    ]
