# Generated by Django 5.2.8 on 2026-02-20 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0012_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
